spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trx
    username: trx
    password: trx123
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: okteto
    password: okteto
    connection-timeout: 2000

server.port: 0